### PR TITLE
Truffle @ 0.11 is at Maven central. Updating the simplelanguage to work with it

### PR DESCRIPTION
**Pull request by jtulach**
Trying to keep up-to-date in our sample simple language repository.

### CODE REVIEW

**Comment by chrisseaton** [comment]
I presume this is waiting until a compatible GraalVM is available.

**Comment by jtulach** [comment]
There is truffle-0.11 branch already. This change could be merged into it now, imho.

----- Reply message -----
Od: "Chris Seaton" <notifications@github.com>
Komu: "graalvm/simplelanguage" <simplelanguage@noreply.github.com>
Kopie: "Jaroslav Tulach" <jaroslav.tulach@oracle.com>
Předmět: [simplelanguage] Truffle @ 0.11 is at Maven central. Updating the simplelanguage to work with it (#3)
Datum: čt, úno 11, 2016 13:31

I presume this is waiting until a compatible GraalVM is available.

&mdash;

**Comment by chrisseaton** [comment]
Ok I'll wait for GraalVM to be released and then merge the both of them.

**Comment by jtulach** [comment]
I see that #4 is merged into truffle-0.11 branch. Great.

Should anything else from this PR be merged? I am not sure. I modified a lot of files, mostly because I copied SL sources from truffle repository. That doesn't seem to be necessary - the truffle-0.11 branch compiles and runs OK.

I'll close this request without merging.

**Pull request closed without merging**
