### PR TITLE
minor improvements to README.ml

### PR DESCRIPTION
**Pull request by mbrantner**

### CODE REVIEW

**Comment by chumer** [comment]
atm simple language is maintained in graalvm/truffle. Can you move your merge request there? Thanks.

**Comment by mbrantner** [comment]
Why does the repo exist then? I couldn't find this readme in the truffle repository.

**Comment by chrisseaton** [comment]
Yes sorry we should update this repository. It's designed to be a base on which people can fork to start their own languages. So you can think of it as a fork itself of Truffle, and so changes to it should go to the upstream of this repo, which is `graalvm/truffle`. I'll fix this up soon.

**Comment by chrisseaton** [comment]
Oh wait a minute - you're right this is just the readme. Sorry, yes we can merge this here.

**Comment by jtulach** [comment]
The simplelanguage in truffle isn't that simple. Over time it evolves as a universal testing language. The real starting point for people that want to begin with something simple should rather be this, separate repository.

**Comment by chumer** [comment]
The simplelanguage is primarily an example language for people to fork. If it is used for testing it should be usable without changes so the primary use-case is not affected. The simple language in the extra repo and the simple language in the Truffle repo are the same thing. Languages for testing specific properties should reside in test projects. 

It seems that simplelanguage was misused a bit in recent evolution. Maybe we should put in some effort to get it "simple" again.

**Comment by chrisseaton** [comment]
> The simple language in the extra repo and the simple language in the Truffle repo are the same thing.

I'll just clarify that this repo is only updated on each release though - so it's not exactly the same as on master of the main Truffle repo.

**Comment by chumer** [comment]
> I'll just clarify that this repo is only updated on each release though - so it's not exactly the same as on master of the main Truffle repo.

Right. Thanks for the clarification.

**Pull request merged**
